live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x=10
y=10

[font]
size=14

[font.normal]
family = "Inconsolata Nerd Font Mono"

[font.bold]
family = "Inconsolata Nerd Font Mono"

[font.italic]
family = "Inconsolata Nerd Font Mono"

[font.bold_italic]
family = "Inconsolata Nerd Font Mono"

[colors.primary]
background = "#121212"
foreground = "#dedede"

[colors.cursor]
text = "#ffffff"
cursor = "#ffa460"

[colors.normal]
black = "#929292"
red = "#e27373"
green = "#94b979"
yellow = "#ffba7b"
blue = "#97bedc"
magenta = "#e1c0fa"
cyan = "#00988e"
white = "#dedede"

[colors.bright]
black = "#bdbdbd"
red = "#ffa1a1"
green = "#bbdeab"
blue = "#b1d8f6"
magenta = "#fbdaff"
cyan = "#1ab2a8"
white = "#ffffff"
